export const GET_RANDOM_QUESTIONS_ATTEMPT = 'GET_RANDOM_QUESTIONS_ATTEMPT';
export const GET_RANDOM_QUESTIONS_SUCCESS = 'GET_RANDOM_QUESTIONS_SUCCESS';
export const GET_RANDOM_QUESTIONS_FAILURE = 'GET_RANDOM_QUESTIONS_FAILURE';
export const ADD_ANSWER = 'ADD_ANSWER';
